name: "dbt_bigquery_monitoring"
version: "0.23.1"
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2

profile: dbt_bigquery_monitoring

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  dbt_bigquery_monitoring:
    +tags:
      - "dbt-bigquery-monitoring"
    information_schema:
      +tags:
        - "dbt-bigquery-monitoring-information-schema"
      # Suppress dbt Fusion warnings for models using run_query() introspection
      # See: https://docs.getdbt.com/docs/fusion/new-concepts#configuring-static_analysis
      tables:
        information_schema_partitions:
          +static_analysis: unsafe
        information_schema_key_column_usage:
          +static_analysis: unsafe
        information_schema_constraint_column_usage:
          +static_analysis: unsafe
      search_indexes:
        +static_analysis: unsafe
    monitoring:
      +on_schema_change: "append_new_columns"
      +tags:
        - "dbt-bigquery-monitoring-datamarts"
      compute:
        +tags:
          - "dbt-bigquery-monitoring-compute"
      storage:
        +tags:
          - "dbt-bigquery-monitoring-storage"
