name: "dbt_bigquery_monitoring"
version: "0.22.0"
require-dbt-version: [">=1.3.0", "<2.0.0"]
config-version: 2

profile: dbt_bigquery_monitoring

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  +start: Jan 1 2017
  dbt_bigquery_monitoring:
    +tags:
      - "dbt-bigquery-monitoring"
    information_schema:
      +tags:
        - "dbt-bigquery-monitoring-information-schema"
    monitoring:
      +on_schema_change: "append_new_columns"
      +tags:
        - "dbt-bigquery-monitoring-datamarts"
      compute:
        +tags:
          - "dbt-bigquery-monitoring-compute"
      storage:
        +tags:
          - "dbt-bigquery-monitoring-storage"
