name: Build base image for CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'Makefile'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: dbt-bigquery-monitoring-base

jobs:
  build-base-image:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR

      - name: Build base image
        run: |
          docker build -t $(IMAGE_NAME):{{ github.branch }} .

      - name: Push base image
        run: |
          docker tag $IMAGE_NAME:{{ github.branch }} $DOCKER_REGISTRY/$IMAGE_NAME:{{ github.branch }}
	        docker push $DOCKER_REGISTRY/$IMAGE_NAME:main

